const baseSet = {
    item: '',
    nature: 'Hardy' as const,
    evs: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 },
    ivs: { hp: 31, atk: 31, def: 31, spa: 31, spd: 31, spe: 31 },
    level: 100,
}

export const hardcodedOpponents = [
    {
        ...baseSet,
        name: 'Garchomp',
        species: 'Garchomp',
        ability: 'Rough Skin',
        moves: ['Earthquake', 'Dragon Claw', 'Stone Edge', 'Swords Dance'],
    },
    {
        ...baseSet,
        name: 'Dragonite',
        species: 'Dragonite',
        ability: 'Multiscale',
        moves: ['Outrage', 'Earthquake', 'Extreme Speed', 'Roost'],
    },
    {
        ...baseSet,
        name: 'Kingambit',
        species: 'Kingambit',
        ability: 'Defiant',
        moves: ['Kowtow Cleave', 'Iron Head', 'Sucker Punch', 'Swords Dance'],
    },
    {
        ...baseSet,
        name: 'Gholdengo',
        species: 'Gholdengo',
        ability: 'Good as Gold',
        moves: ['Shadow Ball', 'Make It Rain', 'Recover', 'Nasty Plot'],
    },
    {
        ...baseSet,
        name: 'Landorus-Therian',
        species: 'Landorus-Therian',
        ability: 'Intimidate',
        moves: ['Earthquake', 'Stone Edge', 'U-turn', 'Stealth Rock'],
    },
    {
        ...baseSet,
        name: 'Great Tusk',
        species: 'Great Tusk',
        ability: 'Protosynthesis',
        moves: ['Headlong Rush', 'Close Combat', 'Knock Off', 'Rapid Spin'],
    },
    {
        ...baseSet,
        name: 'Garganacl',
        species: 'Garganacl',
        ability: 'Purifying Salt',
        moves: ['Salt Cure', 'Body Press', 'Earthquake', 'Recover'],
    },
    {
        ...baseSet,
        name: 'Slowking-Galar',
        species: 'Slowking-Galar',
        ability: 'Regenerator',
        moves: ['Sludge Bomb', 'Future Sight', 'Flamethrower', 'Slack Off'],
    },
    {
        ...baseSet,
        name: 'Volcarona',
        species: 'Volcarona',
        ability: 'Flame Body',
        moves: ['Fiery Dance', 'Giga Drain', 'Bug Buzz', 'Quiver Dance'],
    },
    {
        ...baseSet,
        name: 'Enamorus',
        species: 'Enamorus',
        ability: 'Contrary',
        moves: ['Moonblast', 'Earth Power', 'Psychic', 'Calm Mind'],
    },
    {
        ...baseSet,
        name: 'Iron Moth',
        species: 'Iron Moth',
        ability: 'Quark Drive',
        moves: ['Fiery Dance', 'Sludge Wave', 'Energy Ball', 'Psychic'],
    },
    {
        ...baseSet,
        name: 'Raging Bolt',
        species: 'Raging Bolt',
        ability: 'Protosynthesis',
        moves: ['Thunderclap', 'Thunderbolt', 'Volt Switch', 'Calm Mind'],
    },
    {
        ...baseSet,
        name: 'Iron Crown',
        species: 'Iron Crown',
        ability: 'Quark Drive',
        moves: [
            'Tachyon Cutter',
            'Psychic Noise',
            'Focus Blast',
            'Volt Switch',
        ],
    },
    {
        ...baseSet,
        name: 'Iron Valiant',
        species: 'Iron Valiant',
        ability: 'Quark Drive',
        moves: ['Spirit Break', 'Close Combat', 'Knock Off', 'Moonblast'],
    },
    {
        ...baseSet,
        name: 'Meowscarada',
        species: 'Meowscarada',
        ability: 'Protean',
        moves: ['Flower Trick', 'Knock Off', 'Triple Axel', 'U-turn'],
    },
    {
        ...baseSet,
        name: 'Samurott-Hisui',
        species: 'Samurott-Hisui',
        ability: 'Sharpness',
        moves: ['Ceaseless Edge', 'Aqua Cutter', 'Knock Off', 'Sacred Sword'],
    },
    {
        ...baseSet,
        name: 'Baxcalibur',
        species: 'Baxcalibur',
        ability: 'Thermal Exchange',
        moves: ['Glaive Rush', 'Earthquake', 'Ice Shard', 'Swords Dance'],
    },
    {
        ...baseSet,
        name: 'Dragapult',
        species: 'Dragapult',
        ability: 'Clear Body',
        moves: ['Dragon Darts', 'Shadow Ball', 'U-turn', 'Will-O-Wisp'],
    },
    {
        ...baseSet,
        name: 'Skeledirge',
        species: 'Skeledirge',
        ability: 'Unaware',
        moves: ['Torch Song', 'Shadow Ball', 'Earth Power', 'Slack Off'],
    },
    {
        ...baseSet,
        name: 'Ting-Lu',
        species: 'Ting-Lu',
        ability: 'Vessel of Ruin',
        moves: ['Earthquake', 'Stone Edge', 'Ruination', 'Stealth Rock'],
    },
]
