const baseSet = {
    item: "",
    nature: "Hardy" as const,
    ability: "",
    evs: { hp: 0, atk: 0, def: 0, spa: 0, spd: 0, spe: 0 },
    ivs: { hp: 31, atk: 31, def: 31, spa: 31, spd: 31, spe: 31 },
    level: 100,
};

export const hardcodedOpponents = [
    {
        ...baseSet,
        name: "Garchomp",
        species: "Garchomp",
        moves: ["Earthquake", "Dragon Claw", "Stone Edge", "Swords Dance"],
    },
    {
        ...baseSet,
        name: "Dragonite",
        species: "Dragonite",
        moves: ["Outrage", "Earthquake", "Extreme Speed", "Roost"],
    },
    {
        ...baseSet,
        name: "Kingambit",
        species: "Kingambit",
        moves: ["Kowtow Cleave", "Iron Head", "Sucker Punch", "Swords Dance"],
    },
    {
        ...baseSet,
        name: "Gholdengo",
        species: "Gholdengo",
        moves: ["Shadow Ball", "Make It Rain", "Recover", "Nasty Plot"],
    },
    {
        ...baseSet,
        name: "Landorus-Therian",
        species: "Landorus-Therian",
        moves: ["Earthquake", "Stone Edge", "U-turn", "Stealth Rock"],
    },
    {
        ...baseSet,
        name: "Great Tusk",
        species: "Great Tusk",
        moves: ["Headlong Rush", "Close Combat", "Knock Off", "Rapid Spin"],
    },
    {
        ...baseSet,
        name: "Garganacl",
        species: "Garganacl",
        moves: ["Salt Cure", "Body Press", "Earthquake", "Recover"],
    },
    {
        ...baseSet,
        name: "Slowking-Galar",
        species: "Slowking-Galar",
        moves: ["Sludge Bomb", "Future Sight", "Flamethrower", "Slack Off"],
    },
    {
        ...baseSet,
        name: "Volcarona",
        species: "Volcarona",
        moves: ["Fiery Dance", "Giga Drain", "Bug Buzz", "Quiver Dance"],
    },
    {
        ...baseSet,
        name: "Enamorus",
        species: "Enamorus",
        moves: ["Moonblast", "Earth Power", "Psychic", "Calm Mind"],
    },
    {
        ...baseSet,
        name: "Iron Moth",
        species: "Iron Moth",
        moves: ["Fiery Dance", "Sludge Wave", "Energy Ball", "Psychic"],
    },
    {
        ...baseSet,
        name: "Raging Bolt",
        species: "Raging Bolt",
        moves: ["Thunderclap", "Thunderbolt", "Volt Switch", "Calm Mind"],
    },
    {
        ...baseSet,
        name: "Iron Crown",
        species: "Iron Crown",
        moves: [
            "Tachyon Cutter",
            "Psychic Noise",
            "Focus Blast",
            "Volt Switch",
        ],
    },
    {
        ...baseSet,
        name: "Iron Valiant",
        species: "Iron Valiant",
        moves: ["Spirit Break", "Close Combat", "Knock Off", "Moonblast"],
    },
    {
        ...baseSet,
        name: "Meowscarada",
        species: "Meowscarada",
        moves: ["Flower Trick", "Knock Off", "Triple Axel", "U-turn"],
    },
    {
        ...baseSet,
        name: "Samurott-Hisui",
        species: "Samurott-Hisui",
        moves: ["Ceaseless Edge", "Aqua Cutter", "Knock Off", "Sacred Sword"],
    },
    {
        ...baseSet,
        name: "Baxcalibur",
        species: "Baxcalibur",
        moves: ["Glaive Rush", "Earthquake", "Ice Shard", "Swords Dance"],
    },
    {
        ...baseSet,
        name: "Dragapult",
        species: "Dragapult",
        moves: ["Dragon Darts", "Shadow Ball", "U-turn", "Will-O-Wisp"],
    },
    {
        ...baseSet,
        name: "Skeledirge",
        species: "Skeledirge",
        moves: ["Torch Song", "Shadow Ball", "Earth Power", "Slack Off"],
    },
    {
        ...baseSet,
        name: "Ting-Lu",
        species: "Ting-Lu",
        moves: ["Earthquake", "Stone Edge", "Ruination", "Stealth Rock"],
    },
];
